export const DEFAULT_EFFECTS = {
  ssao: true,
  ssgi: false,
  shadows: true,
  dof: true,
  bloom: true,
  godrays: true,
  fog: false,
  aces: true,
  ao_dbg: false,
  shd_dbg: false,
  hdr: true,
  auto_exp: false,
  rain: true,
  clouds: true,
};
